/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.polimi.genomics.avro.test2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class myRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3440550726634100078L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"myRecord\",\"namespace\":\"it.polimi.genomics.avro.test2\",\"fields\":[{\"name\":\"myArrayWithMultiplesTypes\",\"type\":{\"type\":\"array\",\"items\":[{\"type\":\"record\",\"name\":\"typeOne\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"typeTwo\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"}]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<myRecord> ENCODER =
      new BinaryMessageEncoder<myRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<myRecord> DECODER =
      new BinaryMessageDecoder<myRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<myRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<myRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<myRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<myRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this myRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a myRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a myRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static myRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<java.lang.Object> myArrayWithMultiplesTypes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public myRecord() {}

  /**
   * All-args constructor.
   * @param myArrayWithMultiplesTypes The new value for myArrayWithMultiplesTypes
   */
  public myRecord(java.util.List<java.lang.Object> myArrayWithMultiplesTypes) {
    this.myArrayWithMultiplesTypes = myArrayWithMultiplesTypes;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return myArrayWithMultiplesTypes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: myArrayWithMultiplesTypes = (java.util.List<java.lang.Object>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'myArrayWithMultiplesTypes' field.
   * @return The value of the 'myArrayWithMultiplesTypes' field.
   */
  public java.util.List<java.lang.Object> getMyArrayWithMultiplesTypes() {
    return myArrayWithMultiplesTypes;
  }


  /**
   * Sets the value of the 'myArrayWithMultiplesTypes' field.
   * @param value the value to set.
   */
  public void setMyArrayWithMultiplesTypes(java.util.List<java.lang.Object> value) {
    this.myArrayWithMultiplesTypes = value;
  }

  /**
   * Creates a new myRecord RecordBuilder.
   * @return A new myRecord RecordBuilder
   */
  public static it.polimi.genomics.avro.test2.myRecord.Builder newBuilder() {
    return new it.polimi.genomics.avro.test2.myRecord.Builder();
  }

  /**
   * Creates a new myRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new myRecord RecordBuilder
   */
  public static it.polimi.genomics.avro.test2.myRecord.Builder newBuilder(it.polimi.genomics.avro.test2.myRecord.Builder other) {
    if (other == null) {
      return new it.polimi.genomics.avro.test2.myRecord.Builder();
    } else {
      return new it.polimi.genomics.avro.test2.myRecord.Builder(other);
    }
  }

  /**
   * Creates a new myRecord RecordBuilder by copying an existing myRecord instance.
   * @param other The existing instance to copy.
   * @return A new myRecord RecordBuilder
   */
  public static it.polimi.genomics.avro.test2.myRecord.Builder newBuilder(it.polimi.genomics.avro.test2.myRecord other) {
    if (other == null) {
      return new it.polimi.genomics.avro.test2.myRecord.Builder();
    } else {
      return new it.polimi.genomics.avro.test2.myRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for myRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<myRecord>
    implements org.apache.avro.data.RecordBuilder<myRecord> {

    private java.util.List<java.lang.Object> myArrayWithMultiplesTypes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.polimi.genomics.avro.test2.myRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.myArrayWithMultiplesTypes)) {
        this.myArrayWithMultiplesTypes = data().deepCopy(fields()[0].schema(), other.myArrayWithMultiplesTypes);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing myRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(it.polimi.genomics.avro.test2.myRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.myArrayWithMultiplesTypes)) {
        this.myArrayWithMultiplesTypes = data().deepCopy(fields()[0].schema(), other.myArrayWithMultiplesTypes);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'myArrayWithMultiplesTypes' field.
      * @return The value.
      */
    public java.util.List<java.lang.Object> getMyArrayWithMultiplesTypes() {
      return myArrayWithMultiplesTypes;
    }


    /**
      * Sets the value of the 'myArrayWithMultiplesTypes' field.
      * @param value The value of 'myArrayWithMultiplesTypes'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.test2.myRecord.Builder setMyArrayWithMultiplesTypes(java.util.List<java.lang.Object> value) {
      validate(fields()[0], value);
      this.myArrayWithMultiplesTypes = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'myArrayWithMultiplesTypes' field has been set.
      * @return True if the 'myArrayWithMultiplesTypes' field has been set, false otherwise.
      */
    public boolean hasMyArrayWithMultiplesTypes() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'myArrayWithMultiplesTypes' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.test2.myRecord.Builder clearMyArrayWithMultiplesTypes() {
      myArrayWithMultiplesTypes = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public myRecord build() {
      try {
        myRecord record = new myRecord();
        record.myArrayWithMultiplesTypes = fieldSetFlags()[0] ? this.myArrayWithMultiplesTypes : (java.util.List<java.lang.Object>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<myRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<myRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<myRecord>
    READER$ = (org.apache.avro.io.DatumReader<myRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










