/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.polimi.genomics.avro.myavro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class gregion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 467206495621998960L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"gregion\",\"namespace\":\"it.polimi.genomics.avro.myavro\",\"fields\":[{\"name\":\"chr\",\"type\":\"string\"},{\"name\":\"start\",\"type\":\"long\"},{\"name\":\"stop\",\"type\":\"long\"},{\"name\":\"strand\",\"type\":\"string\"},{\"name\":\"idsList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"idsList\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"rep\",\"type\":\"int\"}]}}},{\"name\":\"valuesArray\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"sampleRec\",\"fields\":[{\"name\":\"sampleArray\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"repRec\",\"fields\":[{\"name\":\"repArray\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<gregion> ENCODER =
      new BinaryMessageEncoder<gregion>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<gregion> DECODER =
      new BinaryMessageDecoder<gregion>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<gregion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<gregion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<gregion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<gregion>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this gregion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a gregion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a gregion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static gregion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence chr;
   private long start;
   private long stop;
   private java.lang.CharSequence strand;
   private java.util.List<it.polimi.genomics.avro.myavro.idsList> idsList;
   private java.util.List<it.polimi.genomics.avro.myavro.sampleRec> valuesArray;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public gregion() {}

  /**
   * All-args constructor.
   * @param chr The new value for chr
   * @param start The new value for start
   * @param stop The new value for stop
   * @param strand The new value for strand
   * @param idsList The new value for idsList
   * @param valuesArray The new value for valuesArray
   */
  public gregion(java.lang.CharSequence chr, java.lang.Long start, java.lang.Long stop, java.lang.CharSequence strand, java.util.List<it.polimi.genomics.avro.myavro.idsList> idsList, java.util.List<it.polimi.genomics.avro.myavro.sampleRec> valuesArray) {
    this.chr = chr;
    this.start = start;
    this.stop = stop;
    this.strand = strand;
    this.idsList = idsList;
    this.valuesArray = valuesArray;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return chr;
    case 1: return start;
    case 2: return stop;
    case 3: return strand;
    case 4: return idsList;
    case 5: return valuesArray;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: chr = (java.lang.CharSequence)value$; break;
    case 1: start = (java.lang.Long)value$; break;
    case 2: stop = (java.lang.Long)value$; break;
    case 3: strand = (java.lang.CharSequence)value$; break;
    case 4: idsList = (java.util.List<it.polimi.genomics.avro.myavro.idsList>)value$; break;
    case 5: valuesArray = (java.util.List<it.polimi.genomics.avro.myavro.sampleRec>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'chr' field.
   * @return The value of the 'chr' field.
   */
  public java.lang.CharSequence getChr() {
    return chr;
  }


  /**
   * Sets the value of the 'chr' field.
   * @param value the value to set.
   */
  public void setChr(java.lang.CharSequence value) {
    this.chr = value;
  }

  /**
   * Gets the value of the 'start' field.
   * @return The value of the 'start' field.
   */
  public long getStart() {
    return start;
  }


  /**
   * Sets the value of the 'start' field.
   * @param value the value to set.
   */
  public void setStart(long value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'stop' field.
   * @return The value of the 'stop' field.
   */
  public long getStop() {
    return stop;
  }


  /**
   * Sets the value of the 'stop' field.
   * @param value the value to set.
   */
  public void setStop(long value) {
    this.stop = value;
  }

  /**
   * Gets the value of the 'strand' field.
   * @return The value of the 'strand' field.
   */
  public java.lang.CharSequence getStrand() {
    return strand;
  }


  /**
   * Sets the value of the 'strand' field.
   * @param value the value to set.
   */
  public void setStrand(java.lang.CharSequence value) {
    this.strand = value;
  }

  /**
   * Gets the value of the 'idsList' field.
   * @return The value of the 'idsList' field.
   */
  public java.util.List<it.polimi.genomics.avro.myavro.idsList> getIdsList() {
    return idsList;
  }


  /**
   * Sets the value of the 'idsList' field.
   * @param value the value to set.
   */
  public void setIdsList(java.util.List<it.polimi.genomics.avro.myavro.idsList> value) {
    this.idsList = value;
  }

  /**
   * Gets the value of the 'valuesArray' field.
   * @return The value of the 'valuesArray' field.
   */
  public java.util.List<it.polimi.genomics.avro.myavro.sampleRec> getValuesArray() {
    return valuesArray;
  }


  /**
   * Sets the value of the 'valuesArray' field.
   * @param value the value to set.
   */
  public void setValuesArray(java.util.List<it.polimi.genomics.avro.myavro.sampleRec> value) {
    this.valuesArray = value;
  }

  /**
   * Creates a new gregion RecordBuilder.
   * @return A new gregion RecordBuilder
   */
  public static it.polimi.genomics.avro.myavro.gregion.Builder newBuilder() {
    return new it.polimi.genomics.avro.myavro.gregion.Builder();
  }

  /**
   * Creates a new gregion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new gregion RecordBuilder
   */
  public static it.polimi.genomics.avro.myavro.gregion.Builder newBuilder(it.polimi.genomics.avro.myavro.gregion.Builder other) {
    if (other == null) {
      return new it.polimi.genomics.avro.myavro.gregion.Builder();
    } else {
      return new it.polimi.genomics.avro.myavro.gregion.Builder(other);
    }
  }

  /**
   * Creates a new gregion RecordBuilder by copying an existing gregion instance.
   * @param other The existing instance to copy.
   * @return A new gregion RecordBuilder
   */
  public static it.polimi.genomics.avro.myavro.gregion.Builder newBuilder(it.polimi.genomics.avro.myavro.gregion other) {
    if (other == null) {
      return new it.polimi.genomics.avro.myavro.gregion.Builder();
    } else {
      return new it.polimi.genomics.avro.myavro.gregion.Builder(other);
    }
  }

  /**
   * RecordBuilder for gregion instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<gregion>
    implements org.apache.avro.data.RecordBuilder<gregion> {

    private java.lang.CharSequence chr;
    private long start;
    private long stop;
    private java.lang.CharSequence strand;
    private java.util.List<it.polimi.genomics.avro.myavro.idsList> idsList;
    private java.util.List<it.polimi.genomics.avro.myavro.sampleRec> valuesArray;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.polimi.genomics.avro.myavro.gregion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.chr)) {
        this.chr = data().deepCopy(fields()[0].schema(), other.chr);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.start)) {
        this.start = data().deepCopy(fields()[1].schema(), other.start);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.stop)) {
        this.stop = data().deepCopy(fields()[2].schema(), other.stop);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.strand)) {
        this.strand = data().deepCopy(fields()[3].schema(), other.strand);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.idsList)) {
        this.idsList = data().deepCopy(fields()[4].schema(), other.idsList);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.valuesArray)) {
        this.valuesArray = data().deepCopy(fields()[5].schema(), other.valuesArray);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing gregion instance
     * @param other The existing instance to copy.
     */
    private Builder(it.polimi.genomics.avro.myavro.gregion other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.chr)) {
        this.chr = data().deepCopy(fields()[0].schema(), other.chr);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.start)) {
        this.start = data().deepCopy(fields()[1].schema(), other.start);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.stop)) {
        this.stop = data().deepCopy(fields()[2].schema(), other.stop);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.strand)) {
        this.strand = data().deepCopy(fields()[3].schema(), other.strand);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.idsList)) {
        this.idsList = data().deepCopy(fields()[4].schema(), other.idsList);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.valuesArray)) {
        this.valuesArray = data().deepCopy(fields()[5].schema(), other.valuesArray);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'chr' field.
      * @return The value.
      */
    public java.lang.CharSequence getChr() {
      return chr;
    }


    /**
      * Sets the value of the 'chr' field.
      * @param value The value of 'chr'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder setChr(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.chr = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'chr' field has been set.
      * @return True if the 'chr' field has been set, false otherwise.
      */
    public boolean hasChr() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'chr' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder clearChr() {
      chr = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'start' field.
      * @return The value.
      */
    public long getStart() {
      return start;
    }


    /**
      * Sets the value of the 'start' field.
      * @param value The value of 'start'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder setStart(long value) {
      validate(fields()[1], value);
      this.start = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'start' field has been set.
      * @return True if the 'start' field has been set, false otherwise.
      */
    public boolean hasStart() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'start' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder clearStart() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'stop' field.
      * @return The value.
      */
    public long getStop() {
      return stop;
    }


    /**
      * Sets the value of the 'stop' field.
      * @param value The value of 'stop'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder setStop(long value) {
      validate(fields()[2], value);
      this.stop = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'stop' field has been set.
      * @return True if the 'stop' field has been set, false otherwise.
      */
    public boolean hasStop() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'stop' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder clearStop() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'strand' field.
      * @return The value.
      */
    public java.lang.CharSequence getStrand() {
      return strand;
    }


    /**
      * Sets the value of the 'strand' field.
      * @param value The value of 'strand'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder setStrand(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.strand = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'strand' field has been set.
      * @return True if the 'strand' field has been set, false otherwise.
      */
    public boolean hasStrand() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'strand' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder clearStrand() {
      strand = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'idsList' field.
      * @return The value.
      */
    public java.util.List<it.polimi.genomics.avro.myavro.idsList> getIdsList() {
      return idsList;
    }


    /**
      * Sets the value of the 'idsList' field.
      * @param value The value of 'idsList'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder setIdsList(java.util.List<it.polimi.genomics.avro.myavro.idsList> value) {
      validate(fields()[4], value);
      this.idsList = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'idsList' field has been set.
      * @return True if the 'idsList' field has been set, false otherwise.
      */
    public boolean hasIdsList() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'idsList' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder clearIdsList() {
      idsList = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'valuesArray' field.
      * @return The value.
      */
    public java.util.List<it.polimi.genomics.avro.myavro.sampleRec> getValuesArray() {
      return valuesArray;
    }


    /**
      * Sets the value of the 'valuesArray' field.
      * @param value The value of 'valuesArray'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder setValuesArray(java.util.List<it.polimi.genomics.avro.myavro.sampleRec> value) {
      validate(fields()[5], value);
      this.valuesArray = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'valuesArray' field has been set.
      * @return True if the 'valuesArray' field has been set, false otherwise.
      */
    public boolean hasValuesArray() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'valuesArray' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.gregion.Builder clearValuesArray() {
      valuesArray = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public gregion build() {
      try {
        gregion record = new gregion();
        record.chr = fieldSetFlags()[0] ? this.chr : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.start = fieldSetFlags()[1] ? this.start : (java.lang.Long) defaultValue(fields()[1]);
        record.stop = fieldSetFlags()[2] ? this.stop : (java.lang.Long) defaultValue(fields()[2]);
        record.strand = fieldSetFlags()[3] ? this.strand : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.idsList = fieldSetFlags()[4] ? this.idsList : (java.util.List<it.polimi.genomics.avro.myavro.idsList>) defaultValue(fields()[4]);
        record.valuesArray = fieldSetFlags()[5] ? this.valuesArray : (java.util.List<it.polimi.genomics.avro.myavro.sampleRec>) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<gregion>
    WRITER$ = (org.apache.avro.io.DatumWriter<gregion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<gregion>
    READER$ = (org.apache.avro.io.DatumReader<gregion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.chr);

    out.writeLong(this.start);

    out.writeLong(this.stop);

    out.writeString(this.strand);

    long size0 = this.idsList.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (it.polimi.genomics.avro.myavro.idsList e0: this.idsList) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    long size1 = this.valuesArray.size();
    out.writeArrayStart();
    out.setItemCount(size1);
    long actualSize1 = 0;
    for (it.polimi.genomics.avro.myavro.sampleRec e1: this.valuesArray) {
      actualSize1++;
      out.startItem();
      e1.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.chr = in.readString(this.chr instanceof Utf8 ? (Utf8)this.chr : null);

      this.start = in.readLong();

      this.stop = in.readLong();

      this.strand = in.readString(this.strand instanceof Utf8 ? (Utf8)this.strand : null);

      long size0 = in.readArrayStart();
      java.util.List<it.polimi.genomics.avro.myavro.idsList> a0 = this.idsList;
      if (a0 == null) {
        a0 = new SpecificData.Array<it.polimi.genomics.avro.myavro.idsList>((int)size0, SCHEMA$.getField("idsList").schema());
        this.idsList = a0;
      } else a0.clear();
      SpecificData.Array<it.polimi.genomics.avro.myavro.idsList> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<it.polimi.genomics.avro.myavro.idsList>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          it.polimi.genomics.avro.myavro.idsList e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new it.polimi.genomics.avro.myavro.idsList();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      long size1 = in.readArrayStart();
      java.util.List<it.polimi.genomics.avro.myavro.sampleRec> a1 = this.valuesArray;
      if (a1 == null) {
        a1 = new SpecificData.Array<it.polimi.genomics.avro.myavro.sampleRec>((int)size1, SCHEMA$.getField("valuesArray").schema());
        this.valuesArray = a1;
      } else a1.clear();
      SpecificData.Array<it.polimi.genomics.avro.myavro.sampleRec> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<it.polimi.genomics.avro.myavro.sampleRec>)a1 : null);
      for ( ; 0 < size1; size1 = in.arrayNext()) {
        for ( ; size1 != 0; size1--) {
          it.polimi.genomics.avro.myavro.sampleRec e1 = (ga1 != null ? ga1.peek() : null);
          if (e1 == null) {
            e1 = new it.polimi.genomics.avro.myavro.sampleRec();
          }
          e1.customDecode(in);
          a1.add(e1);
        }
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.chr = in.readString(this.chr instanceof Utf8 ? (Utf8)this.chr : null);
          break;

        case 1:
          this.start = in.readLong();
          break;

        case 2:
          this.stop = in.readLong();
          break;

        case 3:
          this.strand = in.readString(this.strand instanceof Utf8 ? (Utf8)this.strand : null);
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<it.polimi.genomics.avro.myavro.idsList> a0 = this.idsList;
          if (a0 == null) {
            a0 = new SpecificData.Array<it.polimi.genomics.avro.myavro.idsList>((int)size0, SCHEMA$.getField("idsList").schema());
            this.idsList = a0;
          } else a0.clear();
          SpecificData.Array<it.polimi.genomics.avro.myavro.idsList> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<it.polimi.genomics.avro.myavro.idsList>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              it.polimi.genomics.avro.myavro.idsList e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new it.polimi.genomics.avro.myavro.idsList();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 5:
          long size1 = in.readArrayStart();
          java.util.List<it.polimi.genomics.avro.myavro.sampleRec> a1 = this.valuesArray;
          if (a1 == null) {
            a1 = new SpecificData.Array<it.polimi.genomics.avro.myavro.sampleRec>((int)size1, SCHEMA$.getField("valuesArray").schema());
            this.valuesArray = a1;
          } else a1.clear();
          SpecificData.Array<it.polimi.genomics.avro.myavro.sampleRec> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<it.polimi.genomics.avro.myavro.sampleRec>)a1 : null);
          for ( ; 0 < size1; size1 = in.arrayNext()) {
            for ( ; size1 != 0; size1--) {
              it.polimi.genomics.avro.myavro.sampleRec e1 = (ga1 != null ? ga1.peek() : null);
              if (e1 == null) {
                e1 = new it.polimi.genomics.avro.myavro.sampleRec();
              }
              e1.customDecode(in);
              a1.add(e1);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










