/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.polimi.genomics.avro.myavro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class idsList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6755422470800230505L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"idsList\",\"namespace\":\"it.polimi.genomics.avro.myavro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"rep\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<idsList> ENCODER =
      new BinaryMessageEncoder<idsList>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<idsList> DECODER =
      new BinaryMessageDecoder<idsList>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<idsList> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<idsList> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<idsList> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<idsList>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this idsList to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a idsList from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a idsList instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static idsList fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private int rep;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public idsList() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param rep The new value for rep
   */
  public idsList(java.lang.Long id, java.lang.Integer rep) {
    this.id = id;
    this.rep = rep;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return rep;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: rep = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'rep' field.
   * @return The value of the 'rep' field.
   */
  public int getRep() {
    return rep;
  }


  /**
   * Sets the value of the 'rep' field.
   * @param value the value to set.
   */
  public void setRep(int value) {
    this.rep = value;
  }

  /**
   * Creates a new idsList RecordBuilder.
   * @return A new idsList RecordBuilder
   */
  public static it.polimi.genomics.avro.myavro.idsList.Builder newBuilder() {
    return new it.polimi.genomics.avro.myavro.idsList.Builder();
  }

  /**
   * Creates a new idsList RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new idsList RecordBuilder
   */
  public static it.polimi.genomics.avro.myavro.idsList.Builder newBuilder(it.polimi.genomics.avro.myavro.idsList.Builder other) {
    if (other == null) {
      return new it.polimi.genomics.avro.myavro.idsList.Builder();
    } else {
      return new it.polimi.genomics.avro.myavro.idsList.Builder(other);
    }
  }

  /**
   * Creates a new idsList RecordBuilder by copying an existing idsList instance.
   * @param other The existing instance to copy.
   * @return A new idsList RecordBuilder
   */
  public static it.polimi.genomics.avro.myavro.idsList.Builder newBuilder(it.polimi.genomics.avro.myavro.idsList other) {
    if (other == null) {
      return new it.polimi.genomics.avro.myavro.idsList.Builder();
    } else {
      return new it.polimi.genomics.avro.myavro.idsList.Builder(other);
    }
  }

  /**
   * RecordBuilder for idsList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<idsList>
    implements org.apache.avro.data.RecordBuilder<idsList> {

    private long id;
    private int rep;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.polimi.genomics.avro.myavro.idsList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.rep)) {
        this.rep = data().deepCopy(fields()[1].schema(), other.rep);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing idsList instance
     * @param other The existing instance to copy.
     */
    private Builder(it.polimi.genomics.avro.myavro.idsList other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.rep)) {
        this.rep = data().deepCopy(fields()[1].schema(), other.rep);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.idsList.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.idsList.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'rep' field.
      * @return The value.
      */
    public int getRep() {
      return rep;
    }


    /**
      * Sets the value of the 'rep' field.
      * @param value The value of 'rep'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.idsList.Builder setRep(int value) {
      validate(fields()[1], value);
      this.rep = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'rep' field has been set.
      * @return True if the 'rep' field has been set, false otherwise.
      */
    public boolean hasRep() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'rep' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.myavro.idsList.Builder clearRep() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public idsList build() {
      try {
        idsList record = new idsList();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.rep = fieldSetFlags()[1] ? this.rep : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<idsList>
    WRITER$ = (org.apache.avro.io.DatumWriter<idsList>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<idsList>
    READER$ = (org.apache.avro.io.DatumReader<idsList>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeInt(this.rep);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.rep = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.rep = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










