/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.polimi.genomics.avro.garray2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** A GArray entity. */
@org.apache.avro.specific.AvroGenerated
public class GArray extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1361133865126596037L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GArray\",\"namespace\":\"it.polimi.genomics.avro.garray2\",\"doc\":\"A GArray entity.\",\"fields\":[{\"name\":\"gRecord\",\"type\":{\"type\":\"record\",\"name\":\"gCoords\",\"fields\":[{\"name\":\"chr\",\"type\":\"string\"},{\"name\":\"start\",\"type\":\"long\"},{\"name\":\"stop\",\"type\":\"long\"},{\"name\":\"strand\",\"type\":\"string\"}]}},{\"name\":\"GAttributesRec\",\"type\":{\"type\":\"record\",\"name\":\"GAttributes\",\"fields\":[{\"name\":\"samples\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"idsRec\",\"fields\":[{\"name\":\"_1\",\"type\":\"long\"},{\"name\":\"_2\",\"type\":\"int\"}]}}},{\"name\":\"att\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":[{\"type\":\"record\",\"name\":\"GDouble\",\"namespace\":\"it.polimi.genomics.avro.core\",\"fields\":[{\"name\":\"v\",\"type\":\"double\"}]},{\"type\":\"record\",\"name\":\"GInt\",\"namespace\":\"it.polimi.genomics.avro.core\",\"fields\":[{\"name\":\"v\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"GNull\",\"namespace\":\"it.polimi.genomics.avro.core\",\"fields\":[]},{\"type\":\"record\",\"name\":\"GString\",\"namespace\":\"it.polimi.genomics.avro.core\",\"fields\":[{\"name\":\"v\",\"type\":\"string\"}]}]}}}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GArray> ENCODER =
      new BinaryMessageEncoder<GArray>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GArray> DECODER =
      new BinaryMessageDecoder<GArray>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GArray> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GArray> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GArray> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GArray>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GArray to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GArray from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GArray instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GArray fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private it.polimi.genomics.avro.garray2.gCoords gRecord;
   private it.polimi.genomics.avro.garray2.GAttributes GAttributesRec;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GArray() {}

  /**
   * All-args constructor.
   * @param gRecord The new value for gRecord
   * @param GAttributesRec The new value for GAttributesRec
   */
  public GArray(it.polimi.genomics.avro.garray2.gCoords gRecord, it.polimi.genomics.avro.garray2.GAttributes GAttributesRec) {
    this.gRecord = gRecord;
    this.GAttributesRec = GAttributesRec;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gRecord;
    case 1: return GAttributesRec;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gRecord = (it.polimi.genomics.avro.garray2.gCoords)value$; break;
    case 1: GAttributesRec = (it.polimi.genomics.avro.garray2.GAttributes)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'gRecord' field.
   * @return The value of the 'gRecord' field.
   */
  public it.polimi.genomics.avro.garray2.gCoords getGRecord() {
    return gRecord;
  }


  /**
   * Sets the value of the 'gRecord' field.
   * @param value the value to set.
   */
  public void setGRecord(it.polimi.genomics.avro.garray2.gCoords value) {
    this.gRecord = value;
  }

  /**
   * Gets the value of the 'GAttributesRec' field.
   * @return The value of the 'GAttributesRec' field.
   */
  public it.polimi.genomics.avro.garray2.GAttributes getGAttributesRec() {
    return GAttributesRec;
  }


  /**
   * Sets the value of the 'GAttributesRec' field.
   * @param value the value to set.
   */
  public void setGAttributesRec(it.polimi.genomics.avro.garray2.GAttributes value) {
    this.GAttributesRec = value;
  }

  /**
   * Creates a new GArray RecordBuilder.
   * @return A new GArray RecordBuilder
   */
  public static it.polimi.genomics.avro.garray2.GArray.Builder newBuilder() {
    return new it.polimi.genomics.avro.garray2.GArray.Builder();
  }

  /**
   * Creates a new GArray RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GArray RecordBuilder
   */
  public static it.polimi.genomics.avro.garray2.GArray.Builder newBuilder(it.polimi.genomics.avro.garray2.GArray.Builder other) {
    if (other == null) {
      return new it.polimi.genomics.avro.garray2.GArray.Builder();
    } else {
      return new it.polimi.genomics.avro.garray2.GArray.Builder(other);
    }
  }

  /**
   * Creates a new GArray RecordBuilder by copying an existing GArray instance.
   * @param other The existing instance to copy.
   * @return A new GArray RecordBuilder
   */
  public static it.polimi.genomics.avro.garray2.GArray.Builder newBuilder(it.polimi.genomics.avro.garray2.GArray other) {
    if (other == null) {
      return new it.polimi.genomics.avro.garray2.GArray.Builder();
    } else {
      return new it.polimi.genomics.avro.garray2.GArray.Builder(other);
    }
  }

  /**
   * RecordBuilder for GArray instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GArray>
    implements org.apache.avro.data.RecordBuilder<GArray> {

    private it.polimi.genomics.avro.garray2.gCoords gRecord;
    private it.polimi.genomics.avro.garray2.gCoords.Builder gRecordBuilder;
    private it.polimi.genomics.avro.garray2.GAttributes GAttributesRec;
    private it.polimi.genomics.avro.garray2.GAttributes.Builder GAttributesRecBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.polimi.genomics.avro.garray2.GArray.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gRecord)) {
        this.gRecord = data().deepCopy(fields()[0].schema(), other.gRecord);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasGRecordBuilder()) {
        this.gRecordBuilder = it.polimi.genomics.avro.garray2.gCoords.newBuilder(other.getGRecordBuilder());
      }
      if (isValidValue(fields()[1], other.GAttributesRec)) {
        this.GAttributesRec = data().deepCopy(fields()[1].schema(), other.GAttributesRec);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasGAttributesRecBuilder()) {
        this.GAttributesRecBuilder = it.polimi.genomics.avro.garray2.GAttributes.newBuilder(other.getGAttributesRecBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing GArray instance
     * @param other The existing instance to copy.
     */
    private Builder(it.polimi.genomics.avro.garray2.GArray other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.gRecord)) {
        this.gRecord = data().deepCopy(fields()[0].schema(), other.gRecord);
        fieldSetFlags()[0] = true;
      }
      this.gRecordBuilder = null;
      if (isValidValue(fields()[1], other.GAttributesRec)) {
        this.GAttributesRec = data().deepCopy(fields()[1].schema(), other.GAttributesRec);
        fieldSetFlags()[1] = true;
      }
      this.GAttributesRecBuilder = null;
    }

    /**
      * Gets the value of the 'gRecord' field.
      * @return The value.
      */
    public it.polimi.genomics.avro.garray2.gCoords getGRecord() {
      return gRecord;
    }


    /**
      * Sets the value of the 'gRecord' field.
      * @param value The value of 'gRecord'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.garray2.GArray.Builder setGRecord(it.polimi.genomics.avro.garray2.gCoords value) {
      validate(fields()[0], value);
      this.gRecordBuilder = null;
      this.gRecord = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gRecord' field has been set.
      * @return True if the 'gRecord' field has been set, false otherwise.
      */
    public boolean hasGRecord() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'gRecord' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public it.polimi.genomics.avro.garray2.gCoords.Builder getGRecordBuilder() {
      if (gRecordBuilder == null) {
        if (hasGRecord()) {
          setGRecordBuilder(it.polimi.genomics.avro.garray2.gCoords.newBuilder(gRecord));
        } else {
          setGRecordBuilder(it.polimi.genomics.avro.garray2.gCoords.newBuilder());
        }
      }
      return gRecordBuilder;
    }

    /**
     * Sets the Builder instance for the 'gRecord' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public it.polimi.genomics.avro.garray2.GArray.Builder setGRecordBuilder(it.polimi.genomics.avro.garray2.gCoords.Builder value) {
      clearGRecord();
      gRecordBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'gRecord' field has an active Builder instance
     * @return True if the 'gRecord' field has an active Builder instance
     */
    public boolean hasGRecordBuilder() {
      return gRecordBuilder != null;
    }

    /**
      * Clears the value of the 'gRecord' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.garray2.GArray.Builder clearGRecord() {
      gRecord = null;
      gRecordBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'GAttributesRec' field.
      * @return The value.
      */
    public it.polimi.genomics.avro.garray2.GAttributes getGAttributesRec() {
      return GAttributesRec;
    }


    /**
      * Sets the value of the 'GAttributesRec' field.
      * @param value The value of 'GAttributesRec'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.garray2.GArray.Builder setGAttributesRec(it.polimi.genomics.avro.garray2.GAttributes value) {
      validate(fields()[1], value);
      this.GAttributesRecBuilder = null;
      this.GAttributesRec = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'GAttributesRec' field has been set.
      * @return True if the 'GAttributesRec' field has been set, false otherwise.
      */
    public boolean hasGAttributesRec() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'GAttributesRec' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public it.polimi.genomics.avro.garray2.GAttributes.Builder getGAttributesRecBuilder() {
      if (GAttributesRecBuilder == null) {
        if (hasGAttributesRec()) {
          setGAttributesRecBuilder(it.polimi.genomics.avro.garray2.GAttributes.newBuilder(GAttributesRec));
        } else {
          setGAttributesRecBuilder(it.polimi.genomics.avro.garray2.GAttributes.newBuilder());
        }
      }
      return GAttributesRecBuilder;
    }

    /**
     * Sets the Builder instance for the 'GAttributesRec' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public it.polimi.genomics.avro.garray2.GArray.Builder setGAttributesRecBuilder(it.polimi.genomics.avro.garray2.GAttributes.Builder value) {
      clearGAttributesRec();
      GAttributesRecBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'GAttributesRec' field has an active Builder instance
     * @return True if the 'GAttributesRec' field has an active Builder instance
     */
    public boolean hasGAttributesRecBuilder() {
      return GAttributesRecBuilder != null;
    }

    /**
      * Clears the value of the 'GAttributesRec' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.garray2.GArray.Builder clearGAttributesRec() {
      GAttributesRec = null;
      GAttributesRecBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GArray build() {
      try {
        GArray record = new GArray();
        if (gRecordBuilder != null) {
          try {
            record.gRecord = this.gRecordBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("gRecord"));
            throw e;
          }
        } else {
          record.gRecord = fieldSetFlags()[0] ? this.gRecord : (it.polimi.genomics.avro.garray2.gCoords) defaultValue(fields()[0]);
        }
        if (GAttributesRecBuilder != null) {
          try {
            record.GAttributesRec = this.GAttributesRecBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("GAttributesRec"));
            throw e;
          }
        } else {
          record.GAttributesRec = fieldSetFlags()[1] ? this.GAttributesRec : (it.polimi.genomics.avro.garray2.GAttributes) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GArray>
    WRITER$ = (org.apache.avro.io.DatumWriter<GArray>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GArray>
    READER$ = (org.apache.avro.io.DatumReader<GArray>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










