/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.polimi.genomics.avro.garray2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class idsRec extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9100847994306192804L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"idsRec\",\"namespace\":\"it.polimi.genomics.avro.garray2\",\"fields\":[{\"name\":\"_1\",\"type\":\"long\"},{\"name\":\"_2\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<idsRec> ENCODER =
      new BinaryMessageEncoder<idsRec>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<idsRec> DECODER =
      new BinaryMessageDecoder<idsRec>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<idsRec> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<idsRec> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<idsRec> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<idsRec>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this idsRec to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a idsRec from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a idsRec instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static idsRec fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long _1;
   private int _2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public idsRec() {}

  /**
   * All-args constructor.
   * @param _1 The new value for _1
   * @param _2 The new value for _2
   */
  public idsRec(java.lang.Long _1, java.lang.Integer _2) {
    this._1 = _1;
    this._2 = _2;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _1;
    case 1: return _2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _1 = (java.lang.Long)value$; break;
    case 1: _2 = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the '_1' field.
   * @return The value of the '_1' field.
   */
  public long get1$1() {
    return _1;
  }


  /**
   * Sets the value of the '_1' field.
   * @param value the value to set.
   */
  public void set1$1(long value) {
    this._1 = value;
  }

  /**
   * Gets the value of the '_2' field.
   * @return The value of the '_2' field.
   */
  public int get2$1() {
    return _2;
  }


  /**
   * Sets the value of the '_2' field.
   * @param value the value to set.
   */
  public void set2$1(int value) {
    this._2 = value;
  }

  /**
   * Creates a new idsRec RecordBuilder.
   * @return A new idsRec RecordBuilder
   */
  public static it.polimi.genomics.avro.garray2.idsRec.Builder newBuilder() {
    return new it.polimi.genomics.avro.garray2.idsRec.Builder();
  }

  /**
   * Creates a new idsRec RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new idsRec RecordBuilder
   */
  public static it.polimi.genomics.avro.garray2.idsRec.Builder newBuilder(it.polimi.genomics.avro.garray2.idsRec.Builder other) {
    if (other == null) {
      return new it.polimi.genomics.avro.garray2.idsRec.Builder();
    } else {
      return new it.polimi.genomics.avro.garray2.idsRec.Builder(other);
    }
  }

  /**
   * Creates a new idsRec RecordBuilder by copying an existing idsRec instance.
   * @param other The existing instance to copy.
   * @return A new idsRec RecordBuilder
   */
  public static it.polimi.genomics.avro.garray2.idsRec.Builder newBuilder(it.polimi.genomics.avro.garray2.idsRec other) {
    if (other == null) {
      return new it.polimi.genomics.avro.garray2.idsRec.Builder();
    } else {
      return new it.polimi.genomics.avro.garray2.idsRec.Builder(other);
    }
  }

  /**
   * RecordBuilder for idsRec instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<idsRec>
    implements org.apache.avro.data.RecordBuilder<idsRec> {

    private long _1;
    private int _2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.polimi.genomics.avro.garray2.idsRec.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._1)) {
        this._1 = data().deepCopy(fields()[0].schema(), other._1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other._2)) {
        this._2 = data().deepCopy(fields()[1].schema(), other._2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing idsRec instance
     * @param other The existing instance to copy.
     */
    private Builder(it.polimi.genomics.avro.garray2.idsRec other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other._1)) {
        this._1 = data().deepCopy(fields()[0].schema(), other._1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other._2)) {
        this._2 = data().deepCopy(fields()[1].schema(), other._2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the '_1' field.
      * @return The value.
      */
    public long get1$1() {
      return _1;
    }


    /**
      * Sets the value of the '_1' field.
      * @param value The value of '_1'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.garray2.idsRec.Builder set1$1(long value) {
      validate(fields()[0], value);
      this._1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the '_1' field has been set.
      * @return True if the '_1' field has been set, false otherwise.
      */
    public boolean has1$1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the '_1' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.garray2.idsRec.Builder clear1$1() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the '_2' field.
      * @return The value.
      */
    public int get2$1() {
      return _2;
    }


    /**
      * Sets the value of the '_2' field.
      * @param value The value of '_2'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.garray2.idsRec.Builder set2$1(int value) {
      validate(fields()[1], value);
      this._2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the '_2' field has been set.
      * @return True if the '_2' field has been set, false otherwise.
      */
    public boolean has2$1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the '_2' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.garray2.idsRec.Builder clear2$1() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public idsRec build() {
      try {
        idsRec record = new idsRec();
        record._1 = fieldSetFlags()[0] ? this._1 : (java.lang.Long) defaultValue(fields()[0]);
        record._2 = fieldSetFlags()[1] ? this._2 : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<idsRec>
    WRITER$ = (org.apache.avro.io.DatumWriter<idsRec>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<idsRec>
    READER$ = (org.apache.avro.io.DatumReader<idsRec>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this._1);

    out.writeInt(this._2);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this._1 = in.readLong();

      this._2 = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this._1 = in.readLong();
          break;

        case 1:
          this._2 = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










