/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.polimi.genomics.avro.test;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class repRec extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9178031019200515001L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"repRec\",\"namespace\":\"it.polimi.genomics.avro.test\",\"fields\":[{\"name\":\"repArray\",\"type\":{\"type\":\"array\",\"items\":[\"null\",\"string\",{\"type\":\"map\",\"values\":\"int\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<repRec> ENCODER =
      new BinaryMessageEncoder<repRec>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<repRec> DECODER =
      new BinaryMessageDecoder<repRec>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<repRec> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<repRec> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<repRec> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<repRec>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this repRec to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a repRec from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a repRec instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static repRec fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<java.lang.Object> repArray;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public repRec() {}

  /**
   * All-args constructor.
   * @param repArray The new value for repArray
   */
  public repRec(java.util.List<java.lang.Object> repArray) {
    this.repArray = repArray;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return repArray;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: repArray = (java.util.List<java.lang.Object>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'repArray' field.
   * @return The value of the 'repArray' field.
   */
  public java.util.List<java.lang.Object> getRepArray() {
    return repArray;
  }


  /**
   * Sets the value of the 'repArray' field.
   * @param value the value to set.
   */
  public void setRepArray(java.util.List<java.lang.Object> value) {
    this.repArray = value;
  }

  /**
   * Creates a new repRec RecordBuilder.
   * @return A new repRec RecordBuilder
   */
  public static it.polimi.genomics.avro.test.repRec.Builder newBuilder() {
    return new it.polimi.genomics.avro.test.repRec.Builder();
  }

  /**
   * Creates a new repRec RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new repRec RecordBuilder
   */
  public static it.polimi.genomics.avro.test.repRec.Builder newBuilder(it.polimi.genomics.avro.test.repRec.Builder other) {
    if (other == null) {
      return new it.polimi.genomics.avro.test.repRec.Builder();
    } else {
      return new it.polimi.genomics.avro.test.repRec.Builder(other);
    }
  }

  /**
   * Creates a new repRec RecordBuilder by copying an existing repRec instance.
   * @param other The existing instance to copy.
   * @return A new repRec RecordBuilder
   */
  public static it.polimi.genomics.avro.test.repRec.Builder newBuilder(it.polimi.genomics.avro.test.repRec other) {
    if (other == null) {
      return new it.polimi.genomics.avro.test.repRec.Builder();
    } else {
      return new it.polimi.genomics.avro.test.repRec.Builder(other);
    }
  }

  /**
   * RecordBuilder for repRec instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<repRec>
    implements org.apache.avro.data.RecordBuilder<repRec> {

    private java.util.List<java.lang.Object> repArray;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.polimi.genomics.avro.test.repRec.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.repArray)) {
        this.repArray = data().deepCopy(fields()[0].schema(), other.repArray);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing repRec instance
     * @param other The existing instance to copy.
     */
    private Builder(it.polimi.genomics.avro.test.repRec other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.repArray)) {
        this.repArray = data().deepCopy(fields()[0].schema(), other.repArray);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'repArray' field.
      * @return The value.
      */
    public java.util.List<java.lang.Object> getRepArray() {
      return repArray;
    }


    /**
      * Sets the value of the 'repArray' field.
      * @param value The value of 'repArray'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.test.repRec.Builder setRepArray(java.util.List<java.lang.Object> value) {
      validate(fields()[0], value);
      this.repArray = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'repArray' field has been set.
      * @return True if the 'repArray' field has been set, false otherwise.
      */
    public boolean hasRepArray() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'repArray' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.test.repRec.Builder clearRepArray() {
      repArray = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public repRec build() {
      try {
        repRec record = new repRec();
        record.repArray = fieldSetFlags()[0] ? this.repArray : (java.util.List<java.lang.Object>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<repRec>
    WRITER$ = (org.apache.avro.io.DatumWriter<repRec>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<repRec>
    READER$ = (org.apache.avro.io.DatumReader<repRec>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










