/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.polimi.genomics.avro.test;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class sampleRec extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3468879680976952033L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"sampleRec\",\"namespace\":\"it.polimi.genomics.avro.test\",\"fields\":[{\"name\":\"sampleArray\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"repRec\",\"fields\":[{\"name\":\"repArray\",\"type\":{\"type\":\"array\",\"items\":[\"null\",\"string\",{\"type\":\"map\",\"values\":\"int\"}]}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<sampleRec> ENCODER =
      new BinaryMessageEncoder<sampleRec>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<sampleRec> DECODER =
      new BinaryMessageDecoder<sampleRec>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<sampleRec> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<sampleRec> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<sampleRec> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<sampleRec>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this sampleRec to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a sampleRec from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a sampleRec instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static sampleRec fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<it.polimi.genomics.avro.test.repRec> sampleArray;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public sampleRec() {}

  /**
   * All-args constructor.
   * @param sampleArray The new value for sampleArray
   */
  public sampleRec(java.util.List<it.polimi.genomics.avro.test.repRec> sampleArray) {
    this.sampleArray = sampleArray;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sampleArray;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sampleArray = (java.util.List<it.polimi.genomics.avro.test.repRec>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sampleArray' field.
   * @return The value of the 'sampleArray' field.
   */
  public java.util.List<it.polimi.genomics.avro.test.repRec> getSampleArray() {
    return sampleArray;
  }


  /**
   * Sets the value of the 'sampleArray' field.
   * @param value the value to set.
   */
  public void setSampleArray(java.util.List<it.polimi.genomics.avro.test.repRec> value) {
    this.sampleArray = value;
  }

  /**
   * Creates a new sampleRec RecordBuilder.
   * @return A new sampleRec RecordBuilder
   */
  public static it.polimi.genomics.avro.test.sampleRec.Builder newBuilder() {
    return new it.polimi.genomics.avro.test.sampleRec.Builder();
  }

  /**
   * Creates a new sampleRec RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new sampleRec RecordBuilder
   */
  public static it.polimi.genomics.avro.test.sampleRec.Builder newBuilder(it.polimi.genomics.avro.test.sampleRec.Builder other) {
    if (other == null) {
      return new it.polimi.genomics.avro.test.sampleRec.Builder();
    } else {
      return new it.polimi.genomics.avro.test.sampleRec.Builder(other);
    }
  }

  /**
   * Creates a new sampleRec RecordBuilder by copying an existing sampleRec instance.
   * @param other The existing instance to copy.
   * @return A new sampleRec RecordBuilder
   */
  public static it.polimi.genomics.avro.test.sampleRec.Builder newBuilder(it.polimi.genomics.avro.test.sampleRec other) {
    if (other == null) {
      return new it.polimi.genomics.avro.test.sampleRec.Builder();
    } else {
      return new it.polimi.genomics.avro.test.sampleRec.Builder(other);
    }
  }

  /**
   * RecordBuilder for sampleRec instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<sampleRec>
    implements org.apache.avro.data.RecordBuilder<sampleRec> {

    private java.util.List<it.polimi.genomics.avro.test.repRec> sampleArray;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.polimi.genomics.avro.test.sampleRec.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sampleArray)) {
        this.sampleArray = data().deepCopy(fields()[0].schema(), other.sampleArray);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing sampleRec instance
     * @param other The existing instance to copy.
     */
    private Builder(it.polimi.genomics.avro.test.sampleRec other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sampleArray)) {
        this.sampleArray = data().deepCopy(fields()[0].schema(), other.sampleArray);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'sampleArray' field.
      * @return The value.
      */
    public java.util.List<it.polimi.genomics.avro.test.repRec> getSampleArray() {
      return sampleArray;
    }


    /**
      * Sets the value of the 'sampleArray' field.
      * @param value The value of 'sampleArray'.
      * @return This builder.
      */
    public it.polimi.genomics.avro.test.sampleRec.Builder setSampleArray(java.util.List<it.polimi.genomics.avro.test.repRec> value) {
      validate(fields()[0], value);
      this.sampleArray = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sampleArray' field has been set.
      * @return True if the 'sampleArray' field has been set, false otherwise.
      */
    public boolean hasSampleArray() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sampleArray' field.
      * @return This builder.
      */
    public it.polimi.genomics.avro.test.sampleRec.Builder clearSampleArray() {
      sampleArray = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public sampleRec build() {
      try {
        sampleRec record = new sampleRec();
        record.sampleArray = fieldSetFlags()[0] ? this.sampleArray : (java.util.List<it.polimi.genomics.avro.test.repRec>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<sampleRec>
    WRITER$ = (org.apache.avro.io.DatumWriter<sampleRec>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<sampleRec>
    READER$ = (org.apache.avro.io.DatumReader<sampleRec>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










